### PR TITLE
fix TOC link

### PR DESCRIPTION
**Pull request by mairaw**
@nokura @SonjaSaltzman I think this will fix the build issue we're having with de-de. I just request a build for all locales to update a sample we fixed in the English repo and saw that German was failing

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/framework/configure-apps/file-schema/wcf/mtommessageencoding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/mtommessageencoding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fmtommessageencoding.md)
[docs/framework/configure-apps/file-schema/wcf/nethttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/nethttpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnethttpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/nethttpsbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/nethttpsbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnethttpsbinding.md)
[docs/framework/configure-apps/file-schema/wcf/netmsmqbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/netmsmqbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnetmsmqbinding.md)
[docs/framework/configure-apps/file-schema/wcf/netnamedpipebinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/netnamedpipebinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnetnamedpipebinding.md)
[docs/framework/configure-apps/file-schema/wcf/netpeertcpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/netpeertcpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnetpeertcpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/nettcpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/nettcpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnettcpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/nettcpcontextbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/nettcpcontextbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnettcpcontextbinding.md)
[docs/framework/configure-apps/file-schema/wcf/basichttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/basichttpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fbasichttpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/basichttpcontextbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/basichttpcontextbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fbasichttpcontextbinding.md)
[docs/framework/configure-apps/file-schema/wcf/binarymessageencoding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/binarymessageencoding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fbinarymessageencoding.md)
[docs/framework/configure-apps/file-schema/wcf/bytestreammessageencoding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/bytestreammessageencoding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fbytestreammessageencoding.md)
[docs/framework/configure-apps/file-schema/wcf/textmessageencoding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/textmessageencoding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Ftextmessageencoding.md)
[docs/framework/configure-apps/file-schema/wcf/udpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/udpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fudpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/webhttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/webhttpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwebhttpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/webmessageencoding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/webmessageencoding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwebmessageencoding.md)
[docs/framework/configure-apps/file-schema/wcf/ws2007federationhttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/ws2007federationhttpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fws2007federationhttpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/ws2007httpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/ws2007httpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fws2007httpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/wsdualhttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/wsdualhttpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwsdualhttpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/wsfederationhttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/wsfederationhttpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwsfederationhttpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/wshttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/wshttpbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwshttpbinding.md)
[docs/framework/configure-apps/file-schema/wcf/wshttpcontextbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/wshttpcontextbinding.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwshttpcontextbinding.md)
[docs/framework/data/adonet/sql/linq/boolean-data-types.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/data/adonet/sql/linq/boolean-data-types.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fdata%2Fadonet%2Fsql%2Flinq%2Fboolean-data-types.md)
[docs/framework/windows-workflow-foundation/feature-specifics.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/windows-workflow-foundation/feature-specifics.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fwindows-workflow-foundation%2Ffeature-specifics.md)
[]() | :x:Error | | [Details](#user-content-)
[docs/toc.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/toc.md) | :warning:Warning | | [Details](#user-content-docs%2Ftoc.md)

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fmtommessageencoding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/mtommessageencoding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/mtommessageencoding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnethttpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/nethttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/nethttpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnethttpsbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/nethttpsbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/nethttpsbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnetmsmqbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/netmsmqbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/netmsmqbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnetnamedpipebinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/netnamedpipebinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/netnamedpipebinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnetpeertcpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/netpeertcpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/netpeertcpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnettcpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/nettcpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/nettcpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fnettcpcontextbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/nettcpcontextbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/nettcpcontextbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fbasichttpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/basichttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/basichttpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fbasichttpcontextbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/basichttpcontextbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/basichttpcontextbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fbinarymessageencoding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/binarymessageencoding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/binarymessageencoding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fbytestreammessageencoding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/bytestreammessageencoding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/bytestreammessageencoding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Ftextmessageencoding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/textmessageencoding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/textmessageencoding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fudpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/udpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/udpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwebhttpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/webhttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/webhttpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwebmessageencoding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/webmessageencoding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/webmessageencoding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fws2007federationhttpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/ws2007federationhttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/ws2007federationhttpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fws2007httpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/ws2007httpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/ws2007httpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwsdualhttpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/wsdualhttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/wsdualhttpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwsfederationhttpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/wsfederationhttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/wsfederationhttpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwshttpbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/wshttpbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/wshttpbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fconfigure-apps%2Ffile-schema%2Fwcf%2Fwshttpcontextbinding.md"></a>
### [docs/framework/configure-apps/file-schema/wcf/wshttpcontextbinding.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/configure-apps/file-schema/wcf/wshttpcontextbinding.md)
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fdata%2Fadonet%2Fsql%2Flinq%2Fboolean-data-types.md"></a>
### [docs/framework/data/adonet/sql/linq/boolean-data-types.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/data/adonet/sql/linq/boolean-data-types.md)
 - **[Error]** Markup failed: Path(../Topic/| Operator (C# Reference).md) contains invalid char.
Parameter name: path.

<a name="docs%2Fframework%2Fwindows-workflow-foundation%2Ffeature-specifics.md"></a>
### [docs/framework/windows-workflow-foundation/feature-specifics.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/framework/windows-workflow-foundation/feature-specifics.md)
 - **[Error]** Markup failed: Path(../Topic/ParallelForEach&lt;T&gt; Activity Designer.md) contains invalid char.
Parameter name: path.

<a name=""></a>
### []()
 - **[Error]** Markup failed: Path(../Topic/&lt;readerQuotas&gt;.md) contains invalid char.
Parameter name: path.
 - **[Warning]** Unable to download xref map file from dotnet-xref/_zip/msdnsmallset.yml, details: Could not find a part of the path &#39;W:\z042-s\dotnet-xref\_zip\msdnsmallset.yml&#39;.
 - **[Warning]** Unable to download xref map file from dotnet-xref/_zip/missingapi.yml, details: Could not find a part of the path &#39;W:\z042-s\dotnet-xref\_zip\missingapi.yml&#39;.
 - **[Warning]** Unable to download xref map file from dotnet-xref/_zip/dotnet.zip, details: File not found: W:\z042-s\dotnet-xref/_zip/dotnet.zip
 - **[Warning]** Unable to download xref map file from dotnet-xref/_zip/vs.110.zip, details: File not found: W:\z042-s\dotnet-xref/_zip/vs.110.zip
 - **[Warning]** Unable to download xref map file from dotnet-xref/_zip/vs.140.zip, details: File not found: W:\z042-s\dotnet-xref/_zip/vs.140.zip
 - **[Warning]** Unable to download xref map file from dotnet-xref/_zip/office15.zip, details: File not found: W:\z042-s\dotnet-xref/_zip/office15.zip
 - **Line 152**: **[Warning]** Cannot find local script file W:\z042-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1
 - **Line 152**: **[Warning]** Cannot find local script file W:\z042-s\_dependentPackages\splitToc\tools\run.ps1

<a name="docs%2Ftoc.md"></a>
### [docs/toc.md](https://github.com/dotnet/docs.de-de/blob/mairaw-patch-1/docs/toc.md)
 - **[Warning]** Unable to find either toc.yml or toc.md inside standard/design-guidelines/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside standard/design-guidelines/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside standard/cross-platform/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside standard/cross-platform/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/common-client-technologies/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/wpf/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/winforms/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/wcf/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/common-client-technologies/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/wpf/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/winforms/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/wcf/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/windows-services/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/network-programming/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/net-native/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/security/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/debug-trace-profile/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/performance/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/mef/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/add-ins/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/interop/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/unmanaged-api/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/windows-services/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/network-programming/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/net-native/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/security/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/debug-trace-profile/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/performance/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/mef/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/add-ins/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/interop/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside framework/unmanaged-api/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside visual-basic/reference/language-specification/. Make sure the file is included in config file docfx.json!
 - **[Warning]** Unable to find either toc.yml or toc.md inside visual-basic/reference/language-specification/. Make sure the file is included in config file docfx.json!

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C30%5C5706be96-cb36-77bb-92cc-86daea16cf88%5CPullRequest%5C201709300110543811-46%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aa0zQCnUDLzNHDegqC1s5r74QGi7z2MYUejQYIPxEvc%3D&st=2017-09-30T01%3A13%3A13Z&se=2017-10-01T01%3A23%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mairaw** [comment]
Resolving that issue unlocked new issues. Some of those <readerquotas> links seem like migration issues from CAPS. They point to msdn links in the english version.

**Comment by gosali** [comment]
Hi @mairaw , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@nokura @SonjaSaltzman  @mairaw , Should I merge this PR?

**Comment by nokura** [comment]
This is translation issue. The ( ) should be placed at the end. I will let MOR fix it.

**Pull request merged**
