### PR TITLE
Fixed translation error

### PR DESCRIPTION
**Pull request by pck1980**

### CODE REVIEW

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/language-reference/keywords/null.md](https://github.com/pck1980/docs.de-de/blob/master/docs/csharp/language-reference/keywords/null.md) | :warning:Warning | [View](https://review.docs.microsoft.com/de-de/dotnet/csharp/language-reference/keywords/null?branch=pr-de-de-36) | [Details](#user-content-docs%2Fcsharp%2Flanguage-reference%2Fkeywords%2Fnull.md)

<a name="docs%2Fcsharp%2Flanguage-reference%2Fkeywords%2Fnull.md"></a>
### [docs/csharp/language-reference/keywords/null.md](https://github.com/pck1980/docs.de-de/blob/master/docs/csharp/language-reference/keywords/null.md)
 - **Line 56**: **[Warning]** Invalid file link:(~/docs/visual-basic/language-reference/nothing.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C29%5C5706be96-cb36-77bb-92cc-86daea16cf88%5CPullRequest%5C201708291318561317-36%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @pck1980 , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@pck1980 , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Comment by gosali** [comment]
@mairaw, Could you please change the base branch for this PR from MASTER to LIVE?
Thank you in advance!

**Pull request merged**
