### PR TITLE
Updated bad code formatting and trailing whitespace

### PR DESCRIPTION
**Pull request by rschindhelm-haba**

### CODE REVIEW

**Comment by LisandroSu** [comment]
Hello @rschindhelm-haba ,
		
Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly.

Please, remember to sign the CLA so that this can be merged if accepted.

Thank you for your time and support.
Microsoft C&E Localization Team

**Comment by rschindhelm-haba** [comment]
Hi @LisandroSu,

You're welcome. I recognized that in at least one more language the same mistakes were made. Is there a way for me to update the same document in multiple languages at once?

Regards,
René

**Comment by srvbpigh** [comment]
@rschindhelm-haba:

Nochmals vielen Dank für Ihre Vorschläge. Wir stimmen Ihnen zu und werden diesen PR mergen. Der Vorschlag wird ebenso im nächsten Update des Artikels verwendet.


Viele Grüße

Microsoft DOCS Global Experience Team

**Comment by lichasu** [comment]
Hi @rschindhelm-haba 

It should be fixed in all languages now. 

Thank you again for the suggestion!

**Pull request merged**
